/**
 * Model lab catalog.
 *
 * Generated from the LobeHub icon set (MIT). Each entry names a lab and the
 * light/dark SVG marks served from `/logos`. Individual company logos may also
 * be governed by their owners' trademark and brand-use policies.
 *
 * Regenerate with `pnpm logos:sync`.
 */

export interface ModelLab {
  /** Stable slug persisted on the model row. */
  id: string;
  name: string;
  /** Paths relative to the `/logos` static prefix. */
  light: string;
  dark: string;
}

export const MODEL_LABS: readonly ModelLab[] = [
  {
    id: 'zeroone',
    name: '01.AI',
    light: 'zeroone/zeroone-light.svg',
    dark: 'zeroone/zeroone-dark.svg',
  },
  { id: 'yi', name: '01.AI (Yi)', light: 'yi/yi-light.svg', dark: 'yi/yi-dark.svg' },
  { id: 'ai302', name: '302.AI', light: 'ai302/ai302-light.svg', dark: 'ai302/ai302-dark.svg' },
  { id: 'ai360', name: '360', light: 'ai360/ai360-light.svg', dark: 'ai360/ai360-dark.svg' },
  { id: 'ace', name: 'Ace', light: 'ace/ace-light.svg', dark: 'ace/ace-dark.svg' },
  { id: 'adobe', name: 'Adobe', light: 'adobe/adobe-light.svg', dark: 'adobe/adobe-dark.svg' },
  {
    id: 'adobefirefly',
    name: 'Adobe Firefly',
    light: 'adobefirefly/adobefirefly-light.svg',
    dark: 'adobefirefly/adobefirefly-dark.svg',
  },
  { id: 'agui', name: 'AG-UI', light: 'agui/agui-light.svg', dark: 'agui/agui-dark.svg' },
  {
    id: 'agentvoice',
    name: 'Agent Voice',
    light: 'agentvoice/agentvoice-light.svg',
    dark: 'agentvoice/agentvoice-dark.svg',
  },
  {
    id: 'agnesai',
    name: 'Agnes AI',
    light: 'agnesai/agnesai-light.svg',
    dark: 'agnesai/agnesai-dark.svg',
  },
  {
    id: 'aistudio',
    name: 'AI Studio',
    light: 'aistudio/aistudio-light.svg',
    dark: 'aistudio/aistudio-dark.svg',
  },
  { id: 'ai21', name: 'AI21 Labs', light: 'ai21/ai21-light.svg', dark: 'ai21/ai21-dark.svg' },
  {
    id: 'aihubmix',
    name: 'AiHubMix',
    light: 'aihubmix/aihubmix-light.svg',
    dark: 'aihubmix/aihubmix-dark.svg',
  },
  {
    id: 'aimass',
    name: 'AiMass',
    light: 'aimass/aimass-light.svg',
    dark: 'aimass/aimass-dark.svg',
  },
  {
    id: 'aionlabs',
    name: 'AionLabs',
    light: 'aionlabs/aionlabs-light.svg',
    dark: 'aionlabs/aionlabs-dark.svg',
  },
  {
    id: 'airjelly',
    name: 'AirJelly',
    light: 'airjelly/airjelly-light.svg',
    dark: 'airjelly/airjelly-dark.svg',
  },
  {
    id: 'akashchat',
    name: 'Akash Chat',
    light: 'akashchat/akashchat-light.svg',
    dark: 'akashchat/akashchat-dark.svg',
  },
  {
    id: 'alephalpha',
    name: 'Aleph Alpha',
    light: 'alephalpha/alephalpha-light.svg',
    dark: 'alephalpha/alephalpha-dark.svg',
  },
  {
    id: 'alibaba',
    name: 'Alibaba',
    light: 'alibaba/alibaba-light.svg',
    dark: 'alibaba/alibaba-dark.svg',
  },
  {
    id: 'alibabacloud',
    name: 'Alibaba Cloud',
    light: 'alibabacloud/alibabacloud-light.svg',
    dark: 'alibabacloud/alibabacloud-dark.svg',
  },
  {
    id: 'ai2',
    name: 'Allen Institute for AI',
    light: 'ai2/ai2-light.svg',
    dark: 'ai2/ai2-dark.svg',
  },
  {
    id: 'bedrock',
    name: 'Amazon Bedrock',
    light: 'bedrock/bedrock-light.svg',
    dark: 'bedrock/bedrock-dark.svg',
  },
  { id: 'nova', name: 'Amazon Nova', light: 'nova/nova-light.svg', dark: 'nova/nova-dark.svg' },
  { id: 'amp', name: 'Amp', light: 'amp/amp-light.svg', dark: 'amp/amp-dark.svg' },
  {
    id: 'anspire',
    name: 'Anspire',
    light: 'anspire/anspire-light.svg',
    dark: 'anspire/anspire-dark.svg',
  },
  {
    id: 'antgroup',
    name: 'Ant Group',
    light: 'antgroup/antgroup-light.svg',
    dark: 'antgroup/antgroup-dark.svg',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    light: 'anthropic/anthropic-light.svg',
    dark: 'anthropic/anthropic-dark.svg',
  },
  {
    id: 'antigravity',
    name: 'Antigravity',
    light: 'antigravity/antigravity-light.svg',
    dark: 'antigravity/antigravity-dark.svg',
  },
  {
    id: 'anyscale',
    name: 'Anyscale',
    light: 'anyscale/anyscale-light.svg',
    dark: 'anyscale/anyscale-dark.svg',
  },
  {
    id: 'apertis',
    name: 'Apertis',
    light: 'apertis/apertis-light.svg',
    dark: 'apertis/apertis-dark.svg',
  },
  { id: 'apple', name: 'Apple', light: 'apple/apple-light.svg', dark: 'apple/apple-dark.svg' },
  { id: 'arcee', name: 'Arcee AI', light: 'arcee/arcee-light.svg', dark: 'arcee/arcee-dark.svg' },
  {
    id: 'askverdict',
    name: 'AskVerdict',
    light: 'askverdict/askverdict-light.svg',
    dark: 'askverdict/askverdict-dark.svg',
  },
  {
    id: 'assemblyai',
    name: 'AssemblyAI',
    light: 'assemblyai/assemblyai-light.svg',
    dark: 'assemblyai/assemblyai-dark.svg',
  },
  {
    id: 'atlascloud',
    name: 'Atlas Cloud',
    light: 'atlascloud/atlascloud-light.svg',
    dark: 'atlascloud/atlascloud-dark.svg',
  },
  {
    id: 'automatic',
    name: 'AUTOMATIC1111',
    light: 'automatic/automatic-light.svg',
    dark: 'automatic/automatic-dark.svg',
  },
  { id: 'aws', name: 'AWS', light: 'aws/aws-light.svg', dark: 'aws/aws-dark.svg' },
  { id: 'aya', name: 'Aya', light: 'aya/aya-light.svg', dark: 'aya/aya-dark.svg' },
  { id: 'azure', name: 'Azure', light: 'azure/azure-light.svg', dark: 'azure/azure-dark.svg' },
  {
    id: 'azureai',
    name: 'Azure AI',
    light: 'azureai/azureai-light.svg',
    dark: 'azureai/azureai-dark.svg',
  },
  { id: 'baai', name: 'BAAI', light: 'baai/baai-light.svg', dark: 'baai/baai-dark.svg' },
  {
    id: 'baichuan',
    name: 'Baichuan',
    light: 'baichuan/baichuan-light.svg',
    dark: 'baichuan/baichuan-dark.svg',
  },
  { id: 'baidu', name: 'Baidu', light: 'baidu/baidu-light.svg', dark: 'baidu/baidu-dark.svg' },
  {
    id: 'baiducloud',
    name: 'Baidu Cloud',
    light: 'baiducloud/baiducloud-light.svg',
    dark: 'baiducloud/baiducloud-dark.svg',
  },
  {
    id: 'bailian',
    name: 'Bailian',
    light: 'bailian/bailian-light.svg',
    dark: 'bailian/bailian-dark.svg',
  },
  {
    id: 'baseten',
    name: 'Baseten',
    light: 'baseten/baseten-light.svg',
    dark: 'baseten/baseten-dark.svg',
  },
  {
    id: 'bilibili',
    name: 'Bilibili',
    light: 'bilibili/bilibili-light.svg',
    dark: 'bilibili/bilibili-dark.svg',
  },
  {
    id: 'bilibiliindex',
    name: 'Bilibili Index',
    light: 'bilibiliindex/bilibiliindex-light.svg',
    dark: 'bilibiliindex/bilibiliindex-dark.svg',
  },
  { id: 'bing', name: 'Bing', light: 'bing/bing-light.svg', dark: 'bing/bing-dark.svg' },
  { id: 'bfl', name: 'Black Forest Labs', light: 'bfl/bfl-light.svg', dark: 'bfl/bfl-dark.svg' },
  { id: 'bocha', name: 'Bocha', light: 'bocha/bocha-light.svg', dark: 'bocha/bocha-dark.svg' },
  { id: 'brave', name: 'Brave', light: 'brave/brave-light.svg', dark: 'brave/brave-dark.svg' },
  {
    id: 'briaai',
    name: 'Bria AI',
    light: 'briaai/briaai-light.svg',
    dark: 'briaai/briaai-dark.svg',
  },
  {
    id: 'browserless',
    name: 'Browserless',
    light: 'browserless/browserless-light.svg',
    dark: 'browserless/browserless-dark.svg',
  },
  {
    id: 'burncloud',
    name: 'BurnCloud',
    light: 'burncloud/burncloud-light.svg',
    dark: 'burncloud/burncloud-dark.svg',
  },
  {
    id: 'bytedance',
    name: 'ByteDance',
    light: 'bytedance/bytedance-light.svg',
    dark: 'bytedance/bytedance-dark.svg',
  },
  {
    id: 'capcut',
    name: 'CapCut',
    light: 'capcut/capcut-light.svg',
    dark: 'capcut/capcut-dark.svg',
  },
  {
    id: 'celestoai',
    name: 'Celesto AI',
    light: 'celestoai/celestoai-light.svg',
    dark: 'celestoai/celestoai-dark.svg',
  },
  {
    id: 'centml',
    name: 'CentML',
    light: 'centml/centml-light.svg',
    dark: 'centml/centml-dark.svg',
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    light: 'cerebras/cerebras-light.svg',
    dark: 'cerebras/cerebras-dark.svg',
  },
  {
    id: 'chatglm',
    name: 'ChatGLM',
    light: 'chatglm/chatglm-light.svg',
    dark: 'chatglm/chatglm-dark.svg',
  },
  {
    id: 'cherrystudio',
    name: 'Cherry Studio',
    light: 'cherrystudio/cherrystudio-light.svg',
    dark: 'cherrystudio/cherrystudio-dark.svg',
  },
  {
    id: 'civitai',
    name: 'Civitai',
    light: 'civitai/civitai-light.svg',
    dark: 'civitai/civitai-dark.svg',
  },
  {
    id: 'claude',
    name: 'Claude',
    light: 'claude/claude-light.svg',
    dark: 'claude/claude-dark.svg',
  },
  {
    id: 'claudecode',
    name: 'Claude Code',
    light: 'claudecode/claudecode-light.svg',
    dark: 'claudecode/claudecode-dark.svg',
  },
  { id: 'cline', name: 'Cline', light: 'cline/cline-light.svg', dark: 'cline/cline-dark.svg' },
  {
    id: 'clipdrop',
    name: 'Clipdrop',
    light: 'clipdrop/clipdrop-light.svg',
    dark: 'clipdrop/clipdrop-dark.svg',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    light: 'cloudflare/cloudflare-light.svg',
    dark: 'cloudflare/cloudflare-dark.svg',
  },
  {
    id: 'codebuddy',
    name: 'CodeBuddy',
    light: 'codebuddy/codebuddy-light.svg',
    dark: 'codebuddy/codebuddy-dark.svg',
  },
  {
    id: 'codeflicker',
    name: 'CodeFlicker',
    light: 'codeflicker/codeflicker-light.svg',
    dark: 'codeflicker/codeflicker-dark.svg',
  },
  {
    id: 'codegeex',
    name: 'CodeGeeX',
    light: 'codegeex/codegeex-light.svg',
    dark: 'codegeex/codegeex-dark.svg',
  },
  { id: 'codex', name: 'Codex', light: 'codex/codex-light.svg', dark: 'codex/codex-dark.svg' },
  {
    id: 'cogvideo',
    name: 'Cogvideo',
    light: 'cogvideo/cogvideo.svg',
    dark: 'cogvideo/cogvideo.svg',
  },
  { id: 'cogview', name: 'Cogview', light: 'cogview/cogview.svg', dark: 'cogview/cogview.svg' },
  {
    id: 'cohere',
    name: 'Cohere',
    light: 'cohere/cohere-light.svg',
    dark: 'cohere/cohere-dark.svg',
  },
  {
    id: 'cometapi',
    name: 'CometAPI',
    light: 'cometapi/cometapi-light.svg',
    dark: 'cometapi/cometapi-dark.svg',
  },
  {
    id: 'comfyui',
    name: 'ComfyUI',
    light: 'comfyui/comfyui-light.svg',
    dark: 'comfyui/comfyui-dark.svg',
  },
  {
    id: 'commanda',
    name: 'CommandA',
    light: 'commanda/commanda-light.svg',
    dark: 'commanda/commanda-dark.svg',
  },
  {
    id: 'copilot',
    name: 'Copilot',
    light: 'copilot/copilot-light.svg',
    dark: 'copilot/copilot-dark.svg',
  },
  {
    id: 'copilotkit',
    name: 'CopilotKit',
    light: 'copilotkit/copilotkit-light.svg',
    dark: 'copilotkit/copilotkit-dark.svg',
  },
  { id: 'coqui', name: 'Coqui', light: 'coqui/coqui-light.svg', dark: 'coqui/coqui-dark.svg' },
  { id: 'coze', name: 'Coze', light: 'coze/coze-light.svg', dark: 'coze/coze-dark.svg' },
  {
    id: 'crewai',
    name: 'CrewAI',
    light: 'crewai/crewai-light.svg',
    dark: 'crewai/crewai-dark.svg',
  },
  {
    id: 'crusoe',
    name: 'Crusoe',
    light: 'crusoe/crusoe-light.svg',
    dark: 'crusoe/crusoe-dark.svg',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    light: 'cursor/cursor-light.svg',
    dark: 'cursor/cursor-dark.svg',
  },
  {
    id: 'cybercut',
    name: 'CyberCut',
    light: 'cybercut/cybercut-light.svg',
    dark: 'cybercut/cybercut-dark.svg',
  },
  {
    id: 'dalle',
    name: 'DALL\u00b7E',
    light: 'dalle/dalle-light.svg',
    dark: 'dalle/dalle-dark.svg',
  },
  { id: 'dbrx', name: 'DBRX', light: 'dbrx/dbrx-light.svg', dark: 'dbrx/dbrx-dark.svg' },
  {
    id: 'deepcogito',
    name: 'Deep Cogito',
    light: 'deepcogito/deepcogito-light.svg',
    dark: 'deepcogito/deepcogito-dark.svg',
  },
  {
    id: 'deepai',
    name: 'DeepAI',
    light: 'deepai/deepai-light.svg',
    dark: 'deepai/deepai-dark.svg',
  },
  {
    id: 'deepinfra',
    name: 'DeepInfra',
    light: 'deepinfra/deepinfra-light.svg',
    dark: 'deepinfra/deepinfra-dark.svg',
  },
  { id: 'deepl', name: 'DeepL', light: 'deepl/deepl-light.svg', dark: 'deepl/deepl-dark.svg' },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    light: 'deepseek/deepseek-light.svg',
    dark: 'deepseek/deepseek-dark.svg',
  },
  { id: 'devin', name: 'Devin', light: 'devin/devin-light.svg', dark: 'devin/devin-dark.svg' },
  { id: 'dify', name: 'Dify', light: 'dify/dify-light.svg', dark: 'dify/dify-dark.svg' },
  { id: 'doc2x', name: 'Doc2X', light: 'doc2x/doc2x-light.svg', dark: 'doc2x/doc2x-dark.svg' },
  {
    id: 'docsearch',
    name: 'DocSearch',
    light: 'docsearch/docsearch-light.svg',
    dark: 'docsearch/docsearch-dark.svg',
  },
  {
    id: 'dolphin',
    name: 'Dolphin',
    light: 'dolphin/dolphin-light.svg',
    dark: 'dolphin/dolphin-dark.svg',
  },
  {
    id: 'doubao',
    name: 'Doubao',
    light: 'doubao/doubao-light.svg',
    dark: 'doubao/doubao-dark.svg',
  },
  {
    id: 'dreammachine',
    name: 'Dream Machine',
    light: 'dreammachine/dreammachine-light.svg',
    dark: 'dreammachine/dreammachine-dark.svg',
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    light: 'elevenlabs/elevenlabs-light.svg',
    dark: 'elevenlabs/elevenlabs-dark.svg',
  },
  {
    id: 'elevenx',
    name: 'ElevenX',
    light: 'elevenx/elevenx-light.svg',
    dark: 'elevenx/elevenx-dark.svg',
  },
  {
    id: 'essentialai',
    name: 'Essential AI',
    light: 'essentialai/essentialai-light.svg',
    dark: 'essentialai/essentialai-dark.svg',
  },
  { id: 'exa', name: 'Exa', light: 'exa/exa-light.svg', dark: 'exa/exa-dark.svg' },
  { id: 'fal', name: 'Fal', light: 'fal/fal-light.svg', dark: 'fal/fal-dark.svg' },
  {
    id: 'fastgpt',
    name: 'FastGPT',
    light: 'fastgpt/fastgpt-light.svg',
    dark: 'fastgpt/fastgpt-dark.svg',
  },
  {
    id: 'featherless',
    name: 'Featherless',
    light: 'featherless/featherless-light.svg',
    dark: 'featherless/featherless-dark.svg',
  },
  { id: 'figma', name: 'Figma', light: 'figma/figma-light.svg', dark: 'figma/figma-dark.svg' },
  {
    id: 'firecrawl',
    name: 'Firecrawl',
    light: 'firecrawl/firecrawl-light.svg',
    dark: 'firecrawl/firecrawl-dark.svg',
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    light: 'fireworks/fireworks-light.svg',
    dark: 'fireworks/fireworks-dark.svg',
  },
  {
    id: 'fishaudio',
    name: 'Fish Audio',
    light: 'fishaudio/fishaudio-light.svg',
    dark: 'fishaudio/fishaudio-dark.svg',
  },
  { id: 'flora', name: 'Flora', light: 'flora/flora-light.svg', dark: 'flora/flora-dark.svg' },
  {
    id: 'flowith',
    name: 'Flowith',
    light: 'flowith/flowith-light.svg',
    dark: 'flowith/flowith-dark.svg',
  },
  { id: 'flux', name: 'FLUX', light: 'flux/flux-light.svg', dark: 'flux/flux-dark.svg' },
  {
    id: 'friendli',
    name: 'Friendli',
    light: 'friendli/friendli-light.svg',
    dark: 'friendli/friendli-dark.svg',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    light: 'gemini/gemini-light.svg',
    dark: 'gemini/gemini-dark.svg',
  },
  {
    id: 'geminicli',
    name: 'Gemini CLI',
    light: 'geminicli/geminicli-light.svg',
    dark: 'geminicli/geminicli-dark.svg',
  },
  { id: 'gemma', name: 'Gemma', light: 'gemma/gemma-light.svg', dark: 'gemma/gemma-dark.svg' },
  {
    id: 'giteeai',
    name: 'Giteeai',
    light: 'giteeai/giteeai-light.svg',
    dark: 'giteeai/giteeai-dark.svg',
  },
  {
    id: 'github',
    name: 'GitHub',
    light: 'github/github-light.svg',
    dark: 'github/github-dark.svg',
  },
  {
    id: 'githubcopilot',
    name: 'GitHub Copilot',
    light: 'githubcopilot/githubcopilot-light.svg',
    dark: 'githubcopilot/githubcopilot-dark.svg',
  },
  { id: 'glama', name: 'Glama', light: 'glama/glama-light.svg', dark: 'glama/glama-dark.svg' },
  { id: 'glif', name: 'Glif', light: 'glif/glif-light.svg', dark: 'glif/glif-dark.svg' },
  { id: 'glmv', name: 'GLM-V', light: 'glmv/glmv-light.svg', dark: 'glmv/glmv-dark.svg' },
  {
    id: 'google',
    name: 'Google',
    light: 'google/google-light.svg',
    dark: 'google/google-dark.svg',
  },
  {
    id: 'googlecloud',
    name: 'Google Cloud',
    light: 'googlecloud/googlecloud-light.svg',
    dark: 'googlecloud/googlecloud-dark.svg',
  },
  {
    id: 'colab',
    name: 'Google Colab',
    light: 'colab/colab-light.svg',
    dark: 'colab/colab-dark.svg',
  },
  {
    id: 'deepmind',
    name: 'Google DeepMind',
    light: 'deepmind/deepmind-light.svg',
    dark: 'deepmind/deepmind-dark.svg',
  },
  { id: 'goose', name: 'Goose', light: 'goose/goose-light.svg', dark: 'goose/goose-dark.svg' },
  {
    id: 'gradio',
    name: 'Gradio',
    light: 'gradio/gradio-light.svg',
    dark: 'gradio/gradio-dark.svg',
  },
  {
    id: 'greptile',
    name: 'Greptile',
    light: 'greptile/greptile-light.svg',
    dark: 'greptile/greptile-dark.svg',
  },
  { id: 'grok', name: 'Grok', light: 'grok/grok-light.svg', dark: 'grok/grok-dark.svg' },
  { id: 'groq', name: 'Groq', light: 'groq/groq-light.svg', dark: 'groq/groq-dark.svg' },
  {
    id: 'hailuo',
    name: 'Hailuo',
    light: 'hailuo/hailuo-light.svg',
    dark: 'hailuo/hailuo-dark.svg',
  },
  {
    id: 'haiper',
    name: 'Haiper',
    light: 'haiper/haiper-light.svg',
    dark: 'haiper/haiper-dark.svg',
  },
  {
    id: 'happyhorse',
    name: 'Happy Horse',
    light: 'happyhorse/happyhorse-light.svg',
    dark: 'happyhorse/happyhorse-dark.svg',
  },
  { id: 'hedra', name: 'Hedra', light: 'hedra/hedra-light.svg', dark: 'hedra/hedra-dark.svg' },
  {
    id: 'hermesagent',
    name: 'Hermes',
    light: 'hermesagent/hermesagent-light.svg',
    dark: 'hermesagent/hermesagent-dark.svg',
  },
  {
    id: 'higress',
    name: 'Higress',
    light: 'higress/higress-light.svg',
    dark: 'higress/higress-dark.svg',
  },
  {
    id: 'huawei',
    name: 'Huawei',
    light: 'huawei/huawei-light.svg',
    dark: 'huawei/huawei-dark.svg',
  },
  {
    id: 'huaweicloud',
    name: 'Huawei Cloud',
    light: 'huaweicloud/huaweicloud-light.svg',
    dark: 'huaweicloud/huaweicloud-dark.svg',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    light: 'huggingface/huggingface-light.svg',
    dark: 'huggingface/huggingface-dark.svg',
  },
  {
    id: 'hunyuan',
    name: 'Hunyuan',
    light: 'hunyuan/hunyuan-light.svg',
    dark: 'hunyuan/hunyuan-dark.svg',
  },
  {
    id: 'hyperbolic',
    name: 'Hyperbolic',
    light: 'hyperbolic/hyperbolic-light.svg',
    dark: 'hyperbolic/hyperbolic-dark.svg',
  },
  { id: 'ibm', name: 'IBM', light: 'ibm/ibm-light.svg', dark: 'ibm/ibm-dark.svg' },
  {
    id: 'ideogram',
    name: 'Ideogram',
    light: 'ideogram/ideogram-light.svg',
    dark: 'ideogram/ideogram-dark.svg',
  },
  {
    id: 'iflytekcloud',
    name: 'iFlytek Cloud',
    light: 'iflytekcloud/iflytekcloud-light.svg',
    dark: 'iflytekcloud/iflytekcloud-dark.svg',
  },
  {
    id: 'inception',
    name: 'Inception',
    light: 'inception/inception-light.svg',
    dark: 'inception/inception-dark.svg',
  },
  {
    id: 'inference',
    name: 'Inference.net',
    light: 'inference/inference-light.svg',
    dark: 'inference/inference-dark.svg',
  },
  {
    id: 'infermatic',
    name: 'Infermatic',
    light: 'infermatic/infermatic-light.svg',
    dark: 'infermatic/infermatic-dark.svg',
  },
  {
    id: 'infinigence',
    name: 'Infinigence',
    light: 'infinigence/infinigence-light.svg',
    dark: 'infinigence/infinigence-dark.svg',
  },
  {
    id: 'inflection',
    name: 'Inflection AI',
    light: 'inflection/inflection-light.svg',
    dark: 'inflection/inflection-dark.svg',
  },
  {
    id: 'internlm',
    name: 'InternLM',
    light: 'internlm/internlm-light.svg',
    dark: 'internlm/internlm-dark.svg',
  },
  {
    id: 'jimeng',
    name: 'Jimeng',
    light: 'jimeng/jimeng-light.svg',
    dark: 'jimeng/jimeng-dark.svg',
  },
  { id: 'jina', name: 'Jina AI', light: 'jina/jina-light.svg', dark: 'jina/jina-dark.svg' },
  { id: 'junie', name: 'Junie', light: 'junie/junie-light.svg', dark: 'junie/junie-dark.svg' },
  { id: 'kagi', name: 'Kagi', light: 'kagi/kagi-light.svg', dark: 'kagi/kagi-dark.svg' },
  {
    id: 'kilocode',
    name: 'Kilo Code',
    light: 'kilocode/kilocode-light.svg',
    dark: 'kilocode/kilocode-dark.svg',
  },
  { id: 'kimi', name: 'Kimi', light: 'kimi/kimi-light.svg', dark: 'kimi/kimi-dark.svg' },
  { id: 'kiro', name: 'Kiro', light: 'kiro/kiro-light.svg', dark: 'kiro/kiro-dark.svg' },
  { id: 'kling', name: 'Kling', light: 'kling/kling-light.svg', dark: 'kling/kling-dark.svg' },
  {
    id: 'kluster',
    name: 'Kluster',
    light: 'kluster/kluster-light.svg',
    dark: 'kluster/kluster-dark.svg',
  },
  {
    id: 'kolors',
    name: 'Kolors',
    light: 'kolors/kolors-light.svg',
    dark: 'kolors/kolors-dark.svg',
  },
  { id: 'krea', name: 'Krea', light: 'krea/krea-light.svg', dark: 'krea/krea-dark.svg' },
  {
    id: 'kwaikat',
    name: 'KwaiKat',
    light: 'kwaikat/kwaikat-light.svg',
    dark: 'kwaikat/kwaikat-dark.svg',
  },
  {
    id: 'kwaipilot',
    name: 'KwaiPilot',
    light: 'kwaipilot/kwaipilot-light.svg',
    dark: 'kwaipilot/kwaipilot-dark.svg',
  },
  {
    id: 'lambda',
    name: 'Lambda',
    light: 'lambda/lambda-light.svg',
    dark: 'lambda/lambda-dark.svg',
  },
  {
    id: 'langchain',
    name: 'LangChain',
    light: 'langchain/langchain-light.svg',
    dark: 'langchain/langchain-dark.svg',
  },
  {
    id: 'langfuse',
    name: 'Langfuse',
    light: 'langfuse/langfuse-light.svg',
    dark: 'langfuse/langfuse-dark.svg',
  },
  {
    id: 'langgraph',
    name: 'LangGraph',
    light: 'langgraph/langgraph-light.svg',
    dark: 'langgraph/langgraph-dark.svg',
  },
  {
    id: 'langsmith',
    name: 'LangSmith',
    light: 'langsmith/langsmith-light.svg',
    dark: 'langsmith/langsmith-dark.svg',
  },
  {
    id: 'leptonai',
    name: 'Lepton AI',
    light: 'leptonai/leptonai-light.svg',
    dark: 'leptonai/leptonai-dark.svg',
  },
  { id: 'lg', name: 'LG AI Research', light: 'lg/lg-light.svg', dark: 'lg/lg-dark.svg' },
  {
    id: 'lightricks',
    name: 'Lightricks',
    light: 'lightricks/lightricks-light.svg',
    dark: 'lightricks/lightricks-dark.svg',
  },
  {
    id: 'liquid',
    name: 'Liquid AI',
    light: 'liquid/liquid-light.svg',
    dark: 'liquid/liquid-dark.svg',
  },
  {
    id: 'livekit',
    name: 'LiveKit',
    light: 'livekit/livekit-light.svg',
    dark: 'livekit/livekit-dark.svg',
  },
  {
    id: 'llamaindex',
    name: 'LlamaIndex',
    light: 'llamaindex/llamaindex-light.svg',
    dark: 'llamaindex/llamaindex-dark.svg',
  },
  { id: 'llava', name: 'LLaVA', light: 'llava/llava-light.svg', dark: 'llava/llava-dark.svg' },
  {
    id: 'llmapi',
    name: 'LLM API',
    light: 'llmapi/llmapi-light.svg',
    dark: 'llmapi/llmapi-dark.svg',
  },
  {
    id: 'lmstudio',
    name: 'LM Studio',
    light: 'lmstudio/lmstudio-light.svg',
    dark: 'lmstudio/lmstudio-dark.svg',
  },
  { id: 'lobehub', name: 'LobeHub', light: 'lobehub/lobehub.svg', dark: 'lobehub/lobehub.svg' },
  {
    id: 'longcat',
    name: 'LongCat',
    light: 'longcat/longcat-light.svg',
    dark: 'longcat/longcat-dark.svg',
  },
  {
    id: 'lovable',
    name: 'Lovable',
    light: 'lovable/lovable-light.svg',
    dark: 'lovable/lovable-dark.svg',
  },
  {
    id: 'lovart',
    name: 'Lovart',
    light: 'lovart/lovart-light.svg',
    dark: 'lovart/lovart-dark.svg',
  },
  { id: 'luma', name: 'Luma', light: 'luma/luma-light.svg', dark: 'luma/luma-dark.svg' },
  { id: 'magic', name: 'Magic', light: 'magic/magic-light.svg', dark: 'magic/magic-dark.svg' },
  { id: 'make', name: 'Make', light: 'make/make-light.svg', dark: 'make/make-dark.svg' },
  { id: 'manus', name: 'Manus', light: 'manus/manus-light.svg', dark: 'manus/manus-dark.svg' },
  {
    id: 'mastra',
    name: 'Mastra',
    light: 'mastra/mastra-light.svg',
    dark: 'mastra/mastra-dark.svg',
  },
  { id: 'mcp', name: 'MCP', light: 'mcp/mcp-light.svg', dark: 'mcp/mcp-dark.svg' },
  { id: 'mcpso', name: 'MCP.so', light: 'mcpso/mcpso-light.svg', dark: 'mcpso/mcpso-dark.svg' },
  { id: 'menlo', name: 'Menlo', light: 'menlo/menlo-light.svg', dark: 'menlo/menlo-dark.svg' },
  { id: 'meshy', name: 'Meshy', light: 'meshy/meshy-light.svg', dark: 'meshy/meshy-dark.svg' },
  { id: 'meta', name: 'Meta', light: 'meta/meta-light.svg', dark: 'meta/meta-dark.svg' },
  {
    id: 'metaai',
    name: 'Meta AI',
    light: 'metaai/metaai-light.svg',
    dark: 'metaai/metaai-dark.svg',
  },
  {
    id: 'metagpt',
    name: 'MetaGPT',
    light: 'metagpt/metagpt-light.svg',
    dark: 'metagpt/metagpt-dark.svg',
  },
  {
    id: 'microsoft',
    name: 'Microsoft',
    light: 'microsoft/microsoft-light.svg',
    dark: 'microsoft/microsoft-dark.svg',
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    light: 'midjourney/midjourney-light.svg',
    dark: 'midjourney/midjourney-dark.svg',
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    light: 'minimax/minimax-light.svg',
    dark: 'minimax/minimax-dark.svg',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    light: 'mistral/mistral-light.svg',
    dark: 'mistral/mistral-dark.svg',
  },
  {
    id: 'modelscope',
    name: 'ModelScope',
    light: 'modelscope/modelscope-light.svg',
    dark: 'modelscope/modelscope-dark.svg',
  },
  {
    id: 'monica',
    name: 'Monica',
    light: 'monica/monica-light.svg',
    dark: 'monica/monica-dark.svg',
  },
  {
    id: 'moonshot',
    name: 'Moonshot AI',
    light: 'moonshot/moonshot-light.svg',
    dark: 'moonshot/moonshot-dark.svg',
  },
  { id: 'morph', name: 'Morph', light: 'morph/morph-light.svg', dark: 'morph/morph-dark.svg' },
  { id: 'moxt', name: 'Moxt', light: 'moxt/moxt-light.svg', dark: 'moxt/moxt-dark.svg' },
  {
    id: 'myshell',
    name: 'MyShell',
    light: 'myshell/myshell-light.svg',
    dark: 'myshell/myshell-dark.svg',
  },
  { id: 'n8n', name: 'n8n', light: 'n8n/n8n-light.svg', dark: 'n8n/n8n-dark.svg' },
  {
    id: 'nanobanana',
    name: 'Nano Banana',
    light: 'nanobanana/nanobanana-light.svg',
    dark: 'nanobanana/nanobanana-dark.svg',
  },
  {
    id: 'nebius',
    name: 'Nebius',
    light: 'nebius/nebius-light.svg',
    dark: 'nebius/nebius-dark.svg',
  },
  {
    id: 'newapi',
    name: 'New API',
    light: 'newapi/newapi-light.svg',
    dark: 'newapi/newapi-dark.svg',
  },
  {
    id: 'notebooklm',
    name: 'NotebookLM',
    light: 'notebooklm/notebooklm-light.svg',
    dark: 'notebooklm/notebooklm-dark.svg',
  },
  {
    id: 'notion',
    name: 'Notion',
    light: 'notion/notion-light.svg',
    dark: 'notion/notion-dark.svg',
  },
  {
    id: 'nousresearch',
    name: 'Nous Research',
    light: 'nousresearch/nousresearch-light.svg',
    dark: 'nousresearch/nousresearch-dark.svg',
  },
  {
    id: 'novelai',
    name: 'NovelAI',
    light: 'novelai/novelai-light.svg',
    dark: 'novelai/novelai-dark.svg',
  },
  {
    id: 'novita',
    name: 'Novita AI',
    light: 'novita/novita-light.svg',
    dark: 'novita/novita-dark.svg',
  },
  {
    id: 'nplcloud',
    name: 'NPL Cloud',
    light: 'nplcloud/nplcloud-light.svg',
    dark: 'nplcloud/nplcloud-dark.svg',
  },
  {
    id: 'nvidia',
    name: 'NVIDIA',
    light: 'nvidia/nvidia-light.svg',
    dark: 'nvidia/nvidia-dark.svg',
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    light: 'obsidian/obsidian-light.svg',
    dark: 'obsidian/obsidian-dark.svg',
  },
  {
    id: 'ollama',
    name: 'Ollama',
    light: 'ollama/ollama-light.svg',
    dark: 'ollama/ollama-dark.svg',
  },
  {
    id: 'openwebui',
    name: 'Open WebUI',
    light: 'openwebui/openwebui-light.svg',
    dark: 'openwebui/openwebui-dark.svg',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    light: 'openai/openai-light.svg',
    dark: 'openai/openai-dark.svg',
  },
  {
    id: 'openchat',
    name: 'OpenChat',
    light: 'openchat/openchat-light.svg',
    dark: 'openchat/openchat-dark.svg',
  },
  {
    id: 'openclaw',
    name: 'OpenClaw',
    light: 'openclaw/openclaw-light.svg',
    dark: 'openclaw/openclaw-dark.svg',
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    light: 'opencode/opencode-light.svg',
    dark: 'opencode/opencode-dark.svg',
  },
  {
    id: 'openhands',
    name: 'OpenHands',
    light: 'openhands/openhands-light.svg',
    dark: 'openhands/openhands-dark.svg',
  },
  {
    id: 'openhuman',
    name: 'OpenHuman',
    light: 'openhuman/openhuman-light.svg',
    dark: 'openhuman/openhuman-dark.svg',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    light: 'openrouter/openrouter-light.svg',
    dark: 'openrouter/openrouter-dark.svg',
  },
  { id: 'palm', name: 'PaLM', light: 'palm/palm-light.svg', dark: 'palm/palm-dark.svg' },
  {
    id: 'parasail',
    name: 'Parasail',
    light: 'parasail/parasail-light.svg',
    dark: 'parasail/parasail-dark.svg',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    light: 'perplexity/perplexity-light.svg',
    dark: 'perplexity/perplexity-dark.svg',
  },
  {
    id: 'phidata',
    name: 'Phidata',
    light: 'phidata/phidata-light.svg',
    dark: 'phidata/phidata-dark.svg',
  },
  { id: 'phind', name: 'Phind', light: 'phind/phind-light.svg', dark: 'phind/phind-dark.svg' },
  { id: 'pi', name: 'Pi', light: 'pi/pi-light.svg', dark: 'pi/pi-dark.svg' },
  { id: 'pika', name: 'Pika', light: 'pika/pika-light.svg', dark: 'pika/pika-dark.svg' },
  {
    id: 'pixverse',
    name: 'PixVerse',
    light: 'pixverse/pixverse-light.svg',
    dark: 'pixverse/pixverse-dark.svg',
  },
  {
    id: 'player2',
    name: 'Player2',
    light: 'player2/player2-light.svg',
    dark: 'player2/player2-dark.svg',
  },
  { id: 'poe', name: 'Poe', light: 'poe/poe-light.svg', dark: 'poe/poe-dark.svg' },
  {
    id: 'pollinations',
    name: 'Pollinations',
    light: 'pollinations/pollinations-light.svg',
    dark: 'pollinations/pollinations-dark.svg',
  },
  {
    id: 'poolside',
    name: 'Poolside',
    light: 'poolside/poolside-light.svg',
    dark: 'poolside/poolside-dark.svg',
  },
  { id: 'ppio', name: 'PPIO', light: 'ppio/ppio-light.svg', dark: 'ppio/ppio-dark.svg' },
  {
    id: 'prunaai',
    name: 'Pruna AI',
    light: 'prunaai/prunaai-light.svg',
    dark: 'prunaai/prunaai-dark.svg',
  },
  {
    id: 'pydanticai',
    name: 'Pydantic AI',
    light: 'pydanticai/pydanticai-light.svg',
    dark: 'pydanticai/pydanticai-dark.svg',
  },
  {
    id: 'qingyan',
    name: 'Qingyan',
    light: 'qingyan/qingyan-light.svg',
    dark: 'qingyan/qingyan-dark.svg',
  },
  { id: 'qiniu', name: 'Qiniu', light: 'qiniu/qiniu-light.svg', dark: 'qiniu/qiniu-dark.svg' },
  { id: 'qoder', name: 'Qoder', light: 'qoder/qoder-light.svg', dark: 'qoder/qoder-dark.svg' },
  { id: 'qwen', name: 'Qwen', light: 'qwen/qwen-light.svg', dark: 'qwen/qwen-dark.svg' },
  {
    id: 'railway',
    name: 'Railway',
    light: 'railway/railway-light.svg',
    dark: 'railway/railway-dark.svg',
  },
  {
    id: 'recraft',
    name: 'Recraft',
    light: 'recraft/recraft-light.svg',
    dark: 'recraft/recraft-dark.svg',
  },
  {
    id: 'relace',
    name: 'Relace',
    light: 'relace/relace-light.svg',
    dark: 'relace/relace-dark.svg',
  },
  {
    id: 'replicate',
    name: 'Replicate',
    light: 'replicate/replicate-light.svg',
    dark: 'replicate/replicate-dark.svg',
  },
  {
    id: 'replit',
    name: 'Replit',
    light: 'replit/replit-light.svg',
    dark: 'replit/replit-dark.svg',
  },
  { id: 'reve', name: 'Reve', light: 'reve/reve-light.svg', dark: 'reve/reve-dark.svg' },
  {
    id: 'roocode',
    name: 'Roo Code',
    light: 'roocode/roocode-light.svg',
    dark: 'roocode/roocode-dark.svg',
  },
  {
    id: 'rsshub',
    name: 'RSSHub',
    light: 'rsshub/rsshub-light.svg',
    dark: 'rsshub/rsshub-dark.svg',
  },
  {
    id: 'runway',
    name: 'Runway',
    light: 'runway/runway-light.svg',
    dark: 'runway/runway-dark.svg',
  },
  { id: 'rwkv', name: 'RWKV', light: 'rwkv/rwkv-light.svg', dark: 'rwkv/rwkv-dark.svg' },
  {
    id: 'sambanova',
    name: 'SambaNova',
    light: 'sambanova/sambanova-light.svg',
    dark: 'sambanova/sambanova-dark.svg',
  },
  {
    id: 'search1api',
    name: 'Search1API',
    light: 'search1api/search1api-light.svg',
    dark: 'search1api/search1api-dark.svg',
  },
  {
    id: 'searchapi',
    name: 'SearchApi',
    light: 'searchapi/searchapi-light.svg',
    dark: 'searchapi/searchapi-dark.svg',
  },
  {
    id: 'searxng',
    name: 'SearXNG',
    light: 'searxng/searxng-light.svg',
    dark: 'searxng/searxng-dark.svg',
  },
  {
    id: 'sensenova',
    name: 'SenseNova',
    light: 'sensenova/sensenova-light.svg',
    dark: 'sensenova/sensenova-dark.svg',
  },
  {
    id: 'siliconcloud',
    name: 'SiliconCloud',
    light: 'siliconcloud/siliconcloud-light.svg',
    dark: 'siliconcloud/siliconcloud-dark.svg',
  },
  {
    id: 'sillytavern',
    name: 'SillyTavern',
    light: 'sillytavern/sillytavern-light.svg',
    dark: 'sillytavern/sillytavern-dark.svg',
  },
  {
    id: 'skywork',
    name: 'Skywork',
    light: 'skywork/skywork-light.svg',
    dark: 'skywork/skywork-dark.svg',
  },
  { id: 'slock', name: 'Slock', light: 'slock/slock-light.svg', dark: 'slock/slock-dark.svg' },
  {
    id: 'smithery',
    name: 'Smithery',
    light: 'smithery/smithery-light.svg',
    dark: 'smithery/smithery-dark.svg',
  },
  {
    id: 'snowflake',
    name: 'Snowflake',
    light: 'snowflake/snowflake-light.svg',
    dark: 'snowflake/snowflake-dark.svg',
  },
  {
    id: 'sophnet',
    name: 'SophNet',
    light: 'sophnet/sophnet-light.svg',
    dark: 'sophnet/sophnet-dark.svg',
  },
  { id: 'sora', name: 'Sora', light: 'sora/sora-light.svg', dark: 'sora/sora-dark.svg' },
  { id: 'spark', name: 'Spark', light: 'spark/spark-light.svg', dark: 'spark/spark-dark.svg' },
  {
    id: 'speedai',
    name: 'SpeedAI',
    light: 'speedai/speedai-light.svg',
    dark: 'speedai/speedai-dark.svg',
  },
  {
    id: 'stability',
    name: 'Stability AI',
    light: 'stability/stability-light.svg',
    dark: 'stability/stability-dark.svg',
  },
  {
    id: 'statecloud',
    name: 'State Cloud',
    light: 'statecloud/statecloud-light.svg',
    dark: 'statecloud/statecloud-dark.svg',
  },
  {
    id: 'stepfun',
    name: 'StepFun',
    light: 'stepfun/stepfun-light.svg',
    dark: 'stepfun/stepfun-dark.svg',
  },
  {
    id: 'straico',
    name: 'Straico',
    light: 'straico/straico-light.svg',
    dark: 'straico/straico-dark.svg',
  },
  {
    id: 'streamlake',
    name: 'StreamLake',
    light: 'streamlake/streamlake-light.svg',
    dark: 'streamlake/streamlake-dark.svg',
  },
  {
    id: 'submodel',
    name: 'SubModel',
    light: 'submodel/submodel-light.svg',
    dark: 'submodel/submodel-dark.svg',
  },
  { id: 'suno', name: 'Suno', light: 'suno/suno-light.svg', dark: 'suno/suno-dark.svg' },
  { id: 'sync', name: 'Sync', light: 'sync/sync-light.svg', dark: 'sync/sync-dark.svg' },
  {
    id: 'targon',
    name: 'Targon',
    light: 'targon/targon-light.svg',
    dark: 'targon/targon-dark.svg',
  },
  {
    id: 'tavily',
    name: 'Tavily',
    light: 'tavily/tavily-light.svg',
    dark: 'tavily/tavily-dark.svg',
  },
  {
    id: 'tencent',
    name: 'Tencent',
    light: 'tencent/tencent-light.svg',
    dark: 'tencent/tencent-dark.svg',
  },
  {
    id: 'tencentcloud',
    name: 'Tencent Cloud',
    light: 'tencentcloud/tencentcloud-light.svg',
    dark: 'tencentcloud/tencentcloud-dark.svg',
  },
  {
    id: 'tiangong',
    name: 'Tiangong',
    light: 'tiangong/tiangong-light.svg',
    dark: 'tiangong/tiangong-dark.svg',
  },
  { id: 'tii', name: 'TII', light: 'tii/tii-light.svg', dark: 'tii/tii-dark.svg' },
  {
    id: 'together',
    name: 'Together AI',
    light: 'together/together-light.svg',
    dark: 'together/together-dark.svg',
  },
  {
    id: 'topazlabs',
    name: 'Topaz Labs',
    light: 'topazlabs/topazlabs-light.svg',
    dark: 'topazlabs/topazlabs-dark.svg',
  },
  { id: 'trae', name: 'Trae', light: 'trae/trae-light.svg', dark: 'trae/trae-dark.svg' },
  { id: 'tripo', name: 'Tripo', light: 'tripo/tripo-light.svg', dark: 'tripo/tripo-dark.svg' },
  { id: 'turix', name: 'Turix', light: 'turix/turix-light.svg', dark: 'turix/turix-dark.svg' },
  { id: 'udio', name: 'Udio', light: 'udio/udio-light.svg', dark: 'udio/udio-dark.svg' },
  {
    id: 'unstructured',
    name: 'Unstructured',
    light: 'unstructured/unstructured-light.svg',
    dark: 'unstructured/unstructured-dark.svg',
  },
  {
    id: 'upstage',
    name: 'Upstage',
    light: 'upstage/upstage-light.svg',
    dark: 'upstage/upstage-dark.svg',
  },
  { id: 'v0', name: 'v0', light: 'v0/v0-light.svg', dark: 'v0/v0-dark.svg' },
  {
    id: 'vectorizerai',
    name: 'Vectorizer AI',
    light: 'vectorizerai/vectorizerai-light.svg',
    dark: 'vectorizerai/vectorizerai-dark.svg',
  },
  {
    id: 'venice',
    name: 'Venice AI',
    light: 'venice/venice-light.svg',
    dark: 'venice/venice-dark.svg',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    light: 'vercel/vercel-light.svg',
    dark: 'vercel/vercel-dark.svg',
  },
  {
    id: 'vertexai',
    name: 'Vertex AI',
    light: 'vertexai/vertexai-light.svg',
    dark: 'vertexai/vertexai-dark.svg',
  },
  { id: 'vidu', name: 'Vidu', light: 'vidu/vidu-light.svg', dark: 'vidu/vidu-dark.svg' },
  {
    id: 'viggle',
    name: 'Viggle',
    light: 'viggle/viggle-light.svg',
    dark: 'viggle/viggle-dark.svg',
  },
  { id: 'vllm', name: 'vLLM', light: 'vllm/vllm-light.svg', dark: 'vllm/vllm-dark.svg' },
  {
    id: 'volcengine',
    name: 'Volcengine',
    light: 'volcengine/volcengine-light.svg',
    dark: 'volcengine/volcengine-dark.svg',
  },
  {
    id: 'voyage',
    name: 'Voyage AI',
    light: 'voyage/voyage-light.svg',
    dark: 'voyage/voyage-dark.svg',
  },
  {
    id: 'wenxin',
    name: 'Wenxin',
    light: 'wenxin/wenxin-light.svg',
    dark: 'wenxin/wenxin-dark.svg',
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    light: 'windsurf/windsurf-light.svg',
    dark: 'windsurf/windsurf-dark.svg',
  },
  {
    id: 'workersai',
    name: 'Workersai',
    light: 'workersai/workersai-light.svg',
    dark: 'workersai/workersai-dark.svg',
  },
  {
    id: 'worldrouter',
    name: 'WorldRouter',
    light: 'worldrouter/worldrouter-light.svg',
    dark: 'worldrouter/worldrouter-dark.svg',
  },
  { id: 'xai', name: 'xAI', light: 'xai/xai-light.svg', dark: 'xai/xai-dark.svg' },
  {
    id: 'xiaomimimo',
    name: 'Xiaomi MiMo',
    light: 'xiaomimimo/xiaomimimo-light.svg',
    dark: 'xiaomimimo/xiaomimimo-dark.svg',
  },
  {
    id: 'xinference',
    name: 'Xinference',
    light: 'xinference/xinference-light.svg',
    dark: 'xinference/xinference-dark.svg',
  },
  { id: 'xpay', name: 'XPay', light: 'xpay/xpay-light.svg', dark: 'xpay/xpay-dark.svg' },
  {
    id: 'xuanyuan',
    name: 'XuanYuan',
    light: 'xuanyuan/xuanyuan-light.svg',
    dark: 'xuanyuan/xuanyuan-dark.svg',
  },
  {
    id: 'yandex',
    name: 'Yandex',
    light: 'yandex/yandex-light.svg',
    dark: 'yandex/yandex-dark.svg',
  },
  {
    id: 'youmind',
    name: 'YouMind',
    light: 'youmind/youmind-light.svg',
    dark: 'youmind/youmind-dark.svg',
  },
  {
    id: 'yuanbao',
    name: 'Yuanbao',
    light: 'yuanbao/yuanbao-light.svg',
    dark: 'yuanbao/yuanbao-dark.svg',
  },
  { id: 'zai', name: 'Z.ai', light: 'zai/zai-light.svg', dark: 'zai/zai-dark.svg' },
  {
    id: 'zapier',
    name: 'Zapier',
    light: 'zapier/zapier-light.svg',
    dark: 'zapier/zapier-dark.svg',
  },
  {
    id: 'zeabur',
    name: 'Zeabur',
    light: 'zeabur/zeabur-light.svg',
    dark: 'zeabur/zeabur-dark.svg',
  },
  {
    id: 'zencoder',
    name: 'Zencoder',
    light: 'zencoder/zencoder-light.svg',
    dark: 'zencoder/zencoder-dark.svg',
  },
  {
    id: 'zenmux',
    name: 'ZenMux',
    light: 'zenmux/zenmux-light.svg',
    dark: 'zenmux/zenmux-dark.svg',
  },
  { id: 'zhipu', name: 'Zhipu AI', light: 'zhipu/zhipu-light.svg', dark: 'zhipu/zhipu-dark.svg' },
] as const;

const LABS_BY_ID = new Map(MODEL_LABS.map((lab) => [lab.id, lab]));

export function findModelLab(id: string | null | undefined): ModelLab | null {
  return id ? (LABS_BY_ID.get(id) ?? null) : null;
}

/** Resolves the public URL for a lab mark in the active theme. */
export function modelLabLogoUrl(lab: ModelLab, mode: 'light' | 'dark'): string {
  return `/logos/${mode === 'dark' ? lab.dark : lab.light}`;
}
